spring:
  profiles:
    include: secret

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      generate-ddl: true
      show-sql: true
      properties:
        hibernate:
          format_sql: true



  # redis Config
redis:
  host: localhost
  port: 6379

# logging
logging:
  level:
    org.apache.http: DEBUG
    httpclient.wire: DEBUG
